name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build"
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install dependencies (linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt -y update
        sudo apt install qtbase5-dev libgl1-mesa-dev

    - name: Install dependencies (windows)
      if: matrix.os == 'windows-latest'
      run: echo "This does nothing"
    - name: Install Qt
      if: matrix.os == 'windows-latest'
      uses: jurplel/install-qt-action@v4
      with:
        host:         windows
        target:       desktop
        arch:         win64_msvc2019_64
        dir:          ${{ runner.temp }}
        setup-python: false 

    - uses: actions/checkout@v4
    - name: build
      run: |
        mkdir build
        cd build
        cmake ../
        make